# Generated by Django 5.2.8 on 2025-11-15 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('employee_id', models.CharField(db_index=True, max_length=50)),
                ('session_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('action_type', models.CharField(db_index=True, max_length=255)),
                ('resource_accessed', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=100)),
                ('request_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'employee_id'], name='whitehat_ap_timesta_e44c2b_idx'), models.Index(fields=['action_type', 'request_status'], name='whitehat_ap_action__a4cf49_idx')],
            },
        ),
    ]
