# Generated by Django 5.2.8 on 2025-11-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitehat_app', '0002_agent_fileupload_offlineevent'),
        ('whitehat_app', '0002_log'),
    ]

    operations = [
    ]
