# Generated by Django 5.2.8 on 2025-11-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitehat_app', '0003_merge_0002_agent_fileupload_offlineevent_0002_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='whitehat_ap_timesta_e44c2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='log',
            name='whitehat_ap_action__a4cf49_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-timestamp'], name='whitehat_ap_timesta_0ed18a_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['employee_id', '-timestamp'], name='whitehat_ap_employe_14da89_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['action_type', '-timestamp'], name='whitehat_ap_action__38f516_idx'),
        ),
    ]
